### ISSUE TITLE
Goldfish event?

### ISSUE THREAD

**Issue by LaFesta1749** [LambdaGaming/RandomGamemode#1]
What is the gold fish gamemode?

**Comment by LambdaGaming** [comment]
Inside joke, it makes a specific player a specific role.

**Comment by LaFesta1749** [comment]
oh, okay. Is it possible for us to add more GameModes or are there going to be added more in the near future and if there's any ETA for it?

**Comment by LambdaGaming** [comment]
None are currently planned but suggestions are welcome.
