### ISSUE TITLE
Randomizer Gamemode issue - round doesn't end.

### ISSUE THREAD

**Issue by LaFesta1749** [LambdaGaming/RandomGamemode#2]
Hello,

The randomizer game mode activates a no-round-end event. The round doesn't end, like, ever. No matter who is alive. SCPs only, chaos or MTF only, etc... It just never ends.

Also is it possible to disable the Friendly Fire that it puts on? Like, add it to the config file or something perhaps?

**Comment by LambdaGaming** [comment]
Friendly fire is required for the randomizer gamemode to work properly. The round will end when there is a single player left alive.

**Comment by LambdaGaming** [comment]
I updated the description in the readme to mention this.
